# Build customization
builds:
  - binary: terraform-provider-tls
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows arm64 is not used and does not compile well as of writing
      - goos: windows
        goarch: arm64

# GitHub release customization
release:
  draft: true
  prerelease: true
